import { environment } from "../environments/environment";

export const avilableLangs = {
    ar: {
       
        employee_create_title: "اضافة موظف جديد",
        employee_name: "اسم الموظف",
        control_pannel: "لوحة التحكم",
        add_new_merit:"اضافة استحقاق جديد",
        please_complete_following_error:"من فضلك اكمل الاخطاء التاليه",
        merit_name_required:"اسم الاستحقاق مطلوب",
        value_required:"قيمة مطلوب",
        merit_name:"اسم الأستحقاق",
        merit_value:"قيمة الأستحقاق",
        percentage:"نسبة مئوية",
        add:"اضافة",
        edit_merit:"تعديل استحقاق ",
        log_in:"تسجيل الدخول",
        email:"البريد الالكتروني",
        email_location_reuired:"الايميل مطلوب",
        email_must_be_correct:"يجب ان يكون الايميل صحيحاً",
        password:"كلمة المرور",
        password_location_reuired:"خانة كلمة المرور مطلوبة",
        password_condition:"كلمه السر يجب ان تحتوي س ارقام و س حروف",
        confirm_deletion:"هل انت متأكد من عملية الحذف؟",
        close:"اغلاق",
        delete:"حذف",
        view_Ministries:"عرض الوزارات",
        add_Ministries:"اضافة وزارة",
        full_name_employ:"اسم الموظف الكامل ",
        full_name_mother:"اسم الأم الكامل",
        phone_number:"رقم الهاتف",
        smart_number:"الرقم الذكي ",
        company_name:"اسم الشركة",
        have_insurance:"لديها تأمين؟",
        date_create:"تاريخ الأنشاء",
        choise:"الخيارات",
        there_is:"يوجد",
        there_isnot:"لا يوجد",
        edit_employee_title: "تعديل موظف",
        directorate_name_reuired:"اسم المديرية مطلوب",
        directorate_condition:"  يجب ان يكون أسم المديرية ما بين ٤ الى ٤٠ حرف",
        full_name_directorate:"اسم المديرية الكامل",
        choose_guarantee_type:"اختر نوع الضمان",
        add_new_employ:"اضافة موظف جديد",
        add_new_deduction:"اضافة استقطاع جديد",
        deduction_name_reuired:"اسم الأستقطاع مطلوب",
        deduction_name:"اسم الأستقطاع",
        governmental:"حكومي",
        edit_new_deduction:"  تعديل استقطاع ",
        view_deduction:"عرض الأستقطاعات",
        add_deduction:"اضافة استقطاع",
        deduction_type:"نوع الأستقطاع",
        deduction_percentage:"الأستقطاع نسبة مئوية ",
        add_circuit:"اضافة دائرة",
        consider_the_following:"يجب مراعاة الاتي",
        circuit_name_reuired:"اسم الدائرة مطلوب",
        circuit_name:"اسم الدائرة",
        edit_circuit:"تعديل الدائرة ",
        view_department:"عرض الاقسام",
        add_department:"اضافة قسم",
        department_name:"اسم القسم",
        placement_employe:"تنسيب الموظف",
        job_role_reuired:"الدور الوظيفي مطلوب",
        department_reuired:"القسم مطلوب",
        job_role:"  الدور الوظيفي",
        date_start:"تاريخ البدء",
        date_end:"تاريخ الأنتهاء",
        state:"الحالة",
        active:"مفعل",
        not_active:"غير مفعل",
        edit:"تعديل",
        add_new_job_role:"اضافة دور وظيفي جديد",
        job_role_name_reuired:"اسم الدور الوظيفي مطلوب",
        salary_reuired:"الراتب مطلوب",
        job_role_name:"اسم الدور الوظيفي ",
        salary:"الراتب",
        edit_job_role:"تعديل الدور الوظيفي",
        add_job_role:"اضافة دور وظيفي",
        first_name:"الاسم الاول",
        middle_name:"الاسم الثاني",
        last_name:"الاسم الثالث",
        surname:"اللقب",
        qi_card_smart_id:"الرقم التعريفي لبطاقة كيكارد",
        public_employee_id:"الرقم الحكومي",
        gender:"الجنس",
        nominal_salary:"الراتب الاسمي",
        total_salary:"الراتب الكلي",
        salary_after_deduction:"الراتب بعد الأستقطاعات",
        date_of_payment_of_salary:"تاريخ دفع الراتب",
        view_payment_info:"الدفعات",
        chosse_date:"اختر التاريخ",
        search:"بحث",
        search_about_employe:"ابحث عن موظف",
        full_name:"لأسم الكامل",
        qi_card_account_number:"رقم حساب كي كارد",
        city:"المحافظة",
        city_number:"رقم المحافضة ",
        gov_family_id:"الرقم العائلي  ",
        deduction_date:" تاريخ الأستقطاع",
        merits:"الأستحقاقات",
        deductions:"الأستقطاعات",
        departmen:"القسم",
        ministries_number:"عدد الوزارات ",
        directorate_number:"عدد المديريات",
        predecessor_type_number:"عدد انواع السلف ",
        predecessor_taken:" السلف المأخوذة",
        users_number:"عدد المستخدمين",
        employs_number:"عدد الموظفين",
        beneficiaries_number:"عدد المستفيدين ",
        Loans_info:"  معلومات القروض",
        choose_directorate:"اختر المديرية",
        choose_ministry:"اختر الوزارة",
        employ_name_required:"اسم الموظف مطلوب",
        employ_name_must_be_between_4_to_40_letter:"يجب ان يكون أسم الموظف ما بين ٤ الى ٤٠ حرف",
        mother_name_must_be_between_4_to_40_letter:"يجب ان يكون أسم الأم ما بين ٤ الى ٤٠ حرف",
        mother_name_required:"اسم الأم مطلوب ",
        phone_number_accept_numbers_only:"رقم الهاتف يقبل ارقام فقط",
        phone_number_must_be_between_10_to_11_number_only:"يجب ان يكون رقم الهاتف ما بين ١٠ الى ١١ رقم",
        smart_number_must_be_between_4_to_40_letter:"يجب ان يكون الرقم الذكي ما بين ٤ الى ٤٠ حرف",
        smart_number_accept_only_numbers:"الرقم الذكي يقبل ارقام فقط",
        smart_number_required:"الرقم الذكي مطلوب",
        ministry_name_required:"اسم الوزارة مطلوب",
        main_info_about_ministry_here:"معلومات اساسية عن الوزارة هنا",
        main_info_about_payment_here:"معلومات اساسية عن الدفعات هنا",
        another_info_here:"معلومات اخرى هنا",
        advance_search:"بحث متقدم",
        department_numbers:"عدد الاقسام",
        sure_password:"قم بتأكيد كلمة المرور ",
        first_name_location_reuired:"خانة الاسم الاول مطلوبة",
        add_new_username:"اضافة مستخدم جديد ",
        sure_password_must_be_identical:"يجب مطابقة تأكيد كلمة المرور بشكل صحيح",
        user_validation:"صلاحية المستخدم",
        counter:"محاسب",
        operator:"مشغل",
        group:"المجموعة",
        sure:"تاكيد",
        placement_number:"عدد التنسيبات",
        logout: 'تسجيل الخروج',
        employ_system:"نظام الموظفين",
        view_employees:" عرض الموظفين",
        view_deductions:" عرض استحقاقات",
        name_of_premium:"اسم العلاوة",
        value_of_premium:"قيمة العلاوة",
        type_of_premium:"نوع العلاوة",
        calculation_of_salaries:"احتساب الرواتب",
        start_calculation:"بدا الاحتساب",
        view_users:"عرض المستخدمين",
        Placement:"تنسيب",
        view_add_sub_circle:"عرض/ اضافة دائرة فرعية",
        statistics:"الاحصائيات",
        employees:"الموظفين",
        merits_and_deductions:"الاستحقاقات والاستقطاعات",
        users:"المستخدمين",
        circuits:"الداوئر",
        view_circuit:"عرض الدوائر",
        view_payment:"عرض الدفعات",
        constant:"ثابتة",
        view_placement:"عرض التنسيبات",
        address:"عنوان السكن",
        id_card_number:"رقم البطاقه ألموحده",
        marital_status:"الحالة الزوجية",
        married:"متزوج", 
        absolute:"مطلق",
        widowed:"أرمل",
        unmarried:"اعزب",
        male:"ذكر",
        female:"انثى",
        full_father_name:"أسم ألأب ألكامل",
        full_mother_name:"أسم الام ألكامل",
        birthdate:"تاريخ الميلاد",
        enrollments_view_title:"عرض التنسيبات",
        create_enrollment:"اضافة تنسيب",
        assign_to:"تنسيب الى",
        assign_date:"تاريخ التنسيب",
        jobgrade:"الدرجة الوظيفية",
        job_level:"الخدمة الوظيفية",
        job_title:"العنوان الوظيفي",
        search_by:"بحث بواسطة",
        name:" الاسم",
        qicard_number:"رقم بطاقة كي كارد",
        job_number:"ألرقم ألوظيفي",
        civil_status_id_number:"رقم هوية الاحوال المدنيه",
        job_titles:"العناوين الوظيفية",
        add_job_title:"اضافة عنوان وظيفي",
        view_job_title:"عرض العناوين الوظيفية",
        job_title_name:"اسم العنوان الوظيفي",
        job_title_name_required:"اسم العنوان الوظيفية مطلوب",
        merit_value_condition:"قيمة الاستحقاق يجب ان تكون اكثر من 0",
        emp_info:" معلومات الموظف",
        salary_info:"معلومات الراتب",
        print:"طباعة",
        final_salary:"الراتب الصافي",
        type:"النوع",
        date:"تاريخ",
        amount:"المبلغ",
        deduction:"الاستقطاع",
        orders:"اوامر",
        non_governmental:" غير حكومي",
        merit:"استحقاق",
        view_info:"عرض المعلومات",
        password_must_be_more_than_6_letters:"كلمة المرور يجب ان تكون اكثر من 6 احرف  ",
        password_confirmation_is_required:"تاكيد كلمة المرور مطلوب",
        full_name_is_required:" الاسم الكامل مطلوب",
        phone_number_must_be_11_digits:" رقم الهاتف يجب ان يكون 11 رقم",
        main_circle:"الدائرة الرئيسية",
        user_placement:"تنسيب المستخدم",
        placement:"تنسيب",
        n1:"الاولى",
        n2:"الثانية",
        n3:"الثالثة",
        n4:"الرابعة",
        n5:"الخامسة",
        n6:"السادسة",
        n7:"السابعة",
        n8:"الثامنه",
        n9:"التاسعة",
        n10:"العاشرة",
        director:"المدير العام ومن بدرجته",
        specail_degree:"الدرجة الخاصة",
        sub_ministry_degree:"وكيل الوزارة ومن بدرجته",
        add_new_job_title:"ضافة عنوان وظيفي جديد",
        logged_successfully:" تم تسجيل الدخول بنجاح",
        data_saved_successfully:" تم حفظ البيانات بنجاح",
        successfully_deleted:"تم الحذف بنجاح",
        there_is_no_data:"لا توجد بيانات",
        username_or_password_is_wrong:"اسم المستخدم او كلمة المرور خاطئة",
        you_are_not_authorized_to_do:" غير مصرح لك بالقيام بهذا الامر",
        please_check_information_entered:"الرجاء التحقق من المعلومات المدخلة",
        insufficient_information:" المعلومات غير كافية",
        something_went_wrong_please_try_again_later:"حدث خطأ ما. يرجى اعادة المحاولة لاحقاً",
        you_are_not_authorize_to_display_this_type_information:" غير مصرح لك اظهار هذا النوع من المعلومات",
        please_wiat:"انتظر من فضلك ...",
        payment_date:" تاريخ الدفعات",
        absence:"الغيابات",
        day_absence:"عدد ايام الغياب",
        view:"عرض",
        statu:"الحالة ",
        disable: "تعطيل تنسيب",
        job_title_short: "العناوين",
        permanent_entitlement:"استحقاق دائم",
        reports:"التقارير",
        sub_department:"الدائرة الفرعية",
        select_main_circle:" اختر الدائرة الرئيسية",
        select_sub_circle:" اختر الدائرة الفرعية",
        uploading_circuit_deduction_reports:"  تحميل تقارير استقطاع الدائرة",
        download_department_reports:" تحميل تقارير الدائرة",
        service:"الخدمة",
        upload_cutout_report:" تحميل تقريرالاستقطاع",
        view_banks:"  عرض المصارف",
        add_bank:"اضافة مصرف",
        bank_name:"أسم المصرف",
        banks:"المصارف",
        bank:"المصرف",
        add_new_bank:"اضافة مصرف جديد",
        bank_name_required:"أسم المصرف مطلوب",
        view_benefit:"عرض استحقاقات",				
        



       
         
        
        
        
        
    },
    en: {
        employee_create_title: "Add New Employee",
        employee_name: "Employee Name",
        control_pannel:"control pannel",
        add_new_merit:"Add New Benefits ",
        please_complete_following_error:"Please complete the following errors",
        merit_name_required:"name of Benefit  is required",
        value_required:"value is required",
        merit_name:"Name Of Benefits ",
        merit_value:" Value Of Benefits",
        percentage:"percent",
        add:"add",
        edit_merit:"Edit Benefits",
        log_in:"log in",
        email:"email", 
        email_location_reuired:" email reuired",
        email_must_be_correct:"Email must be correct",
        password:"password",
        password_location_reuired:"password location reuired",
        // password_condition:"password must be contain from  "+" {{ getConfigValue('forms.validation.password.minLength') }} "+"to "+" {{ getConfigValue('forms.validation.password.maxLength') }}"+"characters and numbers",
        confirm_deletion:"?are sure of the deleting process",
        close:"close",
        delete:"delete",
        view_Ministries:"view ministries",
        add_Ministries:"add a ministry",
        full_name_employ:"full name of employ ",
        full_name_mother:"full mother's name",
        phone_number:"phone number ",
        smart_number:"Smart Number",
        company_name:"company name",
        have_insurance:"have a insurance ?",
        date_create:"date created",
        choise:"Options",
        there_is:"exist",
        there_isnot:"Not Exist",
        edit_employee_title: "edit employee ",
        directorate_name_reuired:"directorate's name Required",
        directorate_condition:"directorate's name must be between 4 and 40 characters",
        full_name_directorate:"full directorate name",
        choose_guarantee_type:"Choose your guarantee type",
        add_new_employ:"Add a new employee",
        add_new_deduction:"add new deduction",
        deduction_name_reuired:"deduction's name is required",
        deduction_name:"deduction's name ",
        governmental:"governmental",
        edit_new_deduction:"edit deduction",
        view_deduction:"view deduction",
        add_deduction:"add deduction",
        deduction_type:" deduction type",
        deduction_percentage:"deduction percent",
        add_circuit:"add department",
        consider_the_following:"Consider the following",
        circuit_name_reuired:"department 's name is required",
        circuit_name:"department 's name",
        edit_circuit:"Edit department",
        view_department:"view department",
        add_department:"add department",
        department_name:"name of department ",
        placement_employe:"Employee enrollment",
        job_role_reuired:"Job role is required",
        department_reuired:" department required",
        job_role:"Job role",
        date_start:"starting date",
        date_end:"End date",
        state:"state",
        active:"active",
        not_active:"not active",
        edit:"edit",
        add_new_job_role:"add new Job role",
        job_role_name_reuired:"Job role name is required",
        salary_reuired:"Salary is required",
        job_role_name:"Job role name ",
        salary:"salary",
        edit_job_role:"edit Job role",
        add_job_role:"add Job role",
        first_name:"first name",
        middle_name:"second name",
        last_name:"third name",
        surname:"nickname",
        qi_card_smart_id:"QiCard smart id",
        public_employee_id:"public employee id",
        gender:"gender",
        nominal_salary:"nominal salary",
        total_salary:"total salary",
        salary_after_deduction:"salary after deduction",
        date_of_payment_of_salary:" date of payment of salary",
        view_payment_info:"Payments",
        chosse_date:"Select Date",
        search:"search",
        search_about_employe:"Look for an employee",
        full_name:"full name",
        qi_card_account_number:"QiCard account number",
        city:"city",
        city_number:"city number",
        gov_family_id:"governmental family id",
        deduction_date:" deduction date",
        merits:"Benefits ",
        deductions:"deductions",
        departmen:"departmen",
        ministries_number:"ministries number",
        directorate_number:" directorate number",
        predecessor_type_number:"predecessor type number",
        predecessor_taken:" predecessor_taken",
        users_number:" number of users",
        employs_number:"Number of Employees",
        beneficiaries_number:"beneficiaries number",
        Loans_info:"Loans information",
        choose_directorate:" select directorate",
        choose_ministry:"select ministry",
        employ_name_required:"Employee name is required",
        employ_name_must_be_between_4_to_40_letter:"The employee's name must be 4 to 40 characters",
        mother_name_must_be_between_4_to_40_letter:"The mother's name must be between 4 and 40 characters",
        mother_name_required:"mother_name_required",
        phone_number_accept_numbers_only:"The phone number accepts numbers only",
        phone_number_must_be_between_10_to_11_number_only:"The phone number must be between 10 and 11 digits",
        smart_number_must_be_between_4_to_40_letter:"Smart Number must be 4 to 40 characters",
        smart_number_accept_only_numbers:"smart number accept only numbers",
        smart_number_required:"smart number required",
        ministry_name_required:"ministry name required",
        main_info_about_ministry_here:"Basic information about the ministry here",
        main_info_about_payment_here:"Basic information about payments here",
        another_info_here:"Other information here",
        advance_search:"advanced search",
        department_numbers:"number of department ",
        sure_password:"Confirm your password",
        first_name_location_reuired:"The first name is required",
        add_new_username:"Add a new user",
        sure_password_must_be_identical:"Password confirmation must match correctly",
        user_validation:"User Validity",
        counter:"Accountant",
        operator:"Operator",
        group:"group",
        sure:"accent",
        placement_number:"Number of enrollment ",
        logout: 'logout ',
        employ_system:"Employees System",
        view_employees:"view employees",
        view_deductions:"view deductions",
        name_of_premium:"value  of premium",
        value_of_premium:"value of premium",
        type_of_premium:"Type of premium",
        calculation_of_salaries:"Calculation of salaries",
        start_calculation:"start calculation ",
        view_users:"view users",
        Placement:"enrollment",
        view_add_sub_circle:"View / add a sub-department",
        statistics:"statistics",
        employees:"employees",
        merits_and_deductions:"Benefits And Deductions",
        users:"users",
        circuits:"departments",
        view_circuit:"view department",
       view_payment:"view payment",
       constant:"constant",
       view_placement:"view enrollment",
       address:" address",
       id_card_number:"ID card number",
       marital_status:"Marital Status",
       married:"married", 
        absolute:"absolute",
        widowed:"widowed",
        unmarried:"unmarried",
        male:"male",
        female:"female",
        full_father_name:"full father name",
        full_mother_name:"full moher name",
        birthdate:"birthdate",
        enrollments_view_title:"view enrollment",
        create_enrollment:"Add enrollment",
        assign_to:"enrollment to",
        assign_date:"enrollment date",
        job_grade:"job degree",
        job_level:"job service",
        job_title:"job title",
        search_by:"search by",
        name:"name",
        qicard_number:"Qicard number",
        job_number:"Job Number",
        civil_status_id_number:"Civil Status ID Number",
        job_titles:"job titles",
        job_title_short:"Titles",
        add_job_title:"add job title",
        view_job_title:"view job titles",
        job_title_name:" name of job title",
        job_title_name_required:"name of job title is required",
        merit_value_condition:"The value of the maturity must be more than 0",
        emp_info:"Employee information",
        salary_info:"Employee information",
        print:"print",
        final_salary:"The final salary",
        type:"type",
        date:"date",
        amount:"amount",
        deduction:"deduction",
        orders:"orders",
        non_governmental:"non-governmental",
        merit:"Benefits",
        view_info:"view information",
        password_must_be_more_than_6_letters:"  Password must be more than 6 letters ",
        password_confirmation_is_required:" Password confirmation is required",
        full_name_is_required:" Full name is required",
        phone_number_must_be_11_digits:"The phone number must be 11 digits",
        main_circle:"Main department",
        user_placement:" User enrollment",
        placement:"enrollment",
        n1:"first",
        n2:"second",
        n3:"third",
        n4:"fourth",
        n5:"fifth",
        n6:"sixth",
        n7:"seventh",
        n8:"eighth",
        n9:"ninth",
        n10:"tenth",
        director:" The Director General is of the same degree",
        specail_degree:" Special degree",
        sub_ministry_degree:"Undersecretary of the Ministry and the degree",
        add_new_job_title:"Add a new job title",
        logged_successfully:"data saved successfully",
        data_saved_successfully:" saved successfully",
        successfully_deleted:"successfully deleted",
        there_is_no_data:"there is no data",
        username_or_password_is_wrong:"username or password is wrong",
        you_are_not_authorized_to_do:"you are not authorized to do",
        please_check_information_entered:"please check information entered",
        insufficient_information:"insufficient information",
        something_went_wrong_please_try_again_later:"something went wrong please try again later",
        you_are_not_authorize_to_display_this_type_information:"you are not authorize to display this type information",
        please_wiat:"please wait",
        payment_date:"payment date",
        absence:"Absences",
        day_absence:"number of absence's Day",
        view:"view",
        statu:"statu",
        permanent_entitlement:"permanent entitlement",
        reports:"report",
        sub_department:"sub department",
        select_main_circle:"Select the main department",
        select_sub_circle:" Select the sub-department",
        uploading_circuit_deduction_reports:"   Uploading department deduction reports",
        download_department_reports:" Download the department reports",
        service:" the service",
        upload_cutout_report:"Upload the deduction report",
        view_banks:"View banks",
        add_bank:"Add a bank",
        bank_name:"Bank Name",
        banks:"Banks",
        add_new_bank:" Add a new bank",
        bank_name_required:"Bank name required",
        view_benefit:"View Benefits ",
        bank:"bank",		    
        	



        
       
         
        
        
    },
    kr: {

    }
};

export function getTranslate(key) {
    let lang = localStorage.getItem('lang');
    if (lang === null || lang === '' ) {
      lang = environment.defaultLang;
    }
    
    return (avilableLangs[lang]) ? avilableLangs[lang][key] : '**' + key + '**';
}