import { Directive, ElementRef, Input } from '@angular/core';
import { environment } from '../environments/environment.prod';
import { avilableLangs } from './lang';

@Directive({
  selector: '[ngxTranslate]'
})
export class TranslateDirective {
  @Input() ngxTranslate: string;
  constructor(private el: ElementRef) {
  }
  
  ngOnInit(): void {
    let lang = localStorage.getItem('lang');

    if (environment.production) {
      let lang = 'ar';
    }
    
    if (this.el.nativeElement.innerText) {
     
      if (lang === null || lang === '' ) {
        lang = environment.defaultLang;
      }
      
      if (avilableLangs[lang][this.ngxTranslate]) {
        this.el.nativeElement.innerText = avilableLangs[lang][this.ngxTranslate];
      }

    }
  }
  

  private ar = {
    employee_create_title: "اضافة موظف جديد",
    employee_name: "اسم الموظف",
    control_pannel:"لوحة التحكم",
    add_new_merit:"اضافة استحقاق جديد",
    please_complete_following_error:"من فضلك اكمل الاخطاء التاليه",
    merit_name_required:"اسم الاستحقاق مطلوب",
    value_required:"قيمة مطلوب",
    merit_name:"اسم الأستحقاق",
    merit_value:"قيمة الأستحقاق",
    percentage:"نسبة مئوية",
    add:"اضافة",
    edit_merit:"تعديل استحقاق ",
    log_in:"تسجيل الدخول",
    email:"البريد الالكتروني",
    email_location_reuired:"خانة الايميل مطلوبة",
    email_must_be_correct:"يجب ان يكون الايميل صحيحاً",
    password:"كلمة المرور",
    password_location_reuired:"خانة كلمة المرور مطلوبة",
    password_condition:"كلمه السر يجب ان تحتوي س ارقام و س حروف",
    confirm_deletion:"هل انت متأكد من عملية الحذف؟",
    close:"اغلاق",
    delete:"",
    view_Ministries:"عرض الوزارات",
    add_Ministries:"اضافة وزارة",
    full_name_employ:"اسم الموظف الكامل ",
    full_name_mother:"اسم الأم الكامل",
    phone_number:"رقم الهاتف",
    smart_number:"الرقم الذكي ",
    company_name:"اسم الشركة",
    have_insurance:"لديها تأمين؟",
    date_create:"تاريخ الأنشاء",
    choise:"الخيارات",
    there_is:"يوجد",
    there_isnot:"لا يوجد",
    edit_employee_title: "تعديل موظف",
    directorate_name_reuired:"اسم المديرية مطلوب",
    directorate_condition:"  يجب ان يكون أسم المديرية ما بين ٤ الى ٤٠ حرف",
    full_name_directorate:"اسم المديرية الكامل",
    choose_guarantee_type:"اختر نوع الضمان",
    add_new_employ:"اضافة موظف جديد",
    add_new_deduction:"اضافة استقطاع جديد",
    deduction_name_reuired:"اسم الأستقطاع مطلوب",
    deduction_name:"اسم الأستقطاع",
    governmental:"حكومي",
    edit_new_deduction:"  تعديل استقطاع ",
    view_deduction:"عرض الأستقطاعات",
    add_deduction:"اضافة استقطاع",
    deduction_type:"نوع الأستقطاع",
    deduction_percentage:"الأستقطاع نسبة مئوية ",
    add_circuit:"اضافة دائرة",
    consider_the_following:"يجب مراعاة الاتي",
    circuit_name_reuired:"اسم الدائرة مطلوب",
    circuit_name:"اسم الدائرة",
    edit_circuit:"تعديل الدائرة ",
    view_department:"عرض الاقسام",
    add_department:"اضافة قسم",
    department_name:"اسم القسم",
    placement_employe:"تنسيب الموظف",
    job_role_reuired:"الدور الوظيفي مطلوب",
    department_reuired:"القسم مطلوب",
    job_role:"  الدور الوظيفي",
    date_start:"تاريخ البدء",
    date_end:"تاريخ الأنتهاء",
    state:"الحالة",
    active:"مفعل",
    not_active:"غير مفعل",
    edit:"تعديل",
    add_new_job_role:"اضافة دور وظيفي جديد",
    job_role_name_reuired:"اسم الدور الوظيفي مطلوب",
    salary_reuired:"الراتب مطلوب",
    job_role_name:"اسم الدور الوظيفي ",
    salary:"الراتب",
    edit_job_role:"تعديل الدور الوظيفي",
    add_job_role:"اضافة دور وظيفي",
    first_name:"الاسم الاول",
    middle_name:"الاسم الثاني",
    last_name:"الاسم الثالث",
    surname:"اللقب",
    qi_card_smart_id:"الرقم التعريفي لبطاقة كيكارد",
    public_employee_id:"الرقم الحكومي",
    gender:"الجنس",
    nominal_salary:"الراتب الاسمي",
    total_salary:"الراتب الكلي",
    salary_after_deduction:"الراتب بعد الأستقطاعات",
    date_of_payment_of_salary:"تاريخ دفع الراتب",
    view_payment_info:"عرض معلومات الدفعات",
    chosse_date:"اختر التاريخ",
    search:"بحث",
    search_about_employe:"ابحث عن موظف",
    full_name:"لأسم الكامل",
    qi_card_account_number:"رقم حساب كي كارد",
    city:"المحافظة",
    city_number:"رقم المحافضة ",
    gov_family_id:"الرقم العائلي  ",
    deduction_date:" تاريخ الأستقطاع",
    merits:"الأستحقاقات",
    deductions:"الأستقطاعات",
    departmen:"القسم",
    ministries_number:"عدد الوزارات ",
    directorate_number:"عدد المديريات",
    predecessor_type_number:"عدد انواع السلف ",
    predecessor_taken:" السلف المأخوذة",
    users_number:"عدد المستخدمين",
    employs_number:"عدد الموظفين",
    beneficiaries_number:"عدد المستخدمين ",
    Loans_info:"  معلومات القروض",
    choose_directorate:"اختر المديرية",
    choose_ministry:"اختر الوزارة",
    employ_name_required:"اسم الموظف مطلوب",
    employ_name_must_be_between_4_to_40_letter:"يجب ان يكون أسم الموظف ما بين ٤ الى ٤٠ حرف",
    mother_name_must_be_between_4_to_40_letter:"يجب ان يكون أسم الأم ما بين ٤ الى ٤٠ حرف",
    mother_name_required:"اسم الأم مطلوب ",
    phone_number_accept_numbers_only:"رقم الهاتف يقبل ارقام فقط",
    phone_number_must_be_between_10_to_11_number_only:"يجب ان يكون رقم الهاتف ما بين ١٠ الى ١١ رقم",
    smart_number_must_be_between_4_to_40_letter:"يجب ان يكون الرقم الذكي ما بين ٤ الى ٤٠ حرف",
    smart_number_accept_only_numbers:"الرقم الذكي يقبل ارقام فقط",
    smart_number_required:"الرقم الذكي مطلوب",
    ministry_name_required:"اسم الوزارة مطلوب",
    main_info_about_ministry_here:"معلومات اساسية عن الوزارة هنا",
    main_info_about_payment_here:"معلومات اساسية عن الدفعات هنا",
    another_info_here:"معلومات اخرى هنا",
    advance_search:"بحث متقدم",
    department_numbers:"عدد الاقسام",
    sure_password:"قم بتأكيد كلمة المرور ",
    first_name_location_reuired:"خانة الاسم الاول مطلوبة",
    add_new_username:"اضافة مستخدم جديد ",
    sure_password_must_be_identical:"يجب مطابقة تأكيد كلمة المرور بشكل صحيح",
    user_validation:"صلاحية المستخدم",
    counter:"محاسب",
    operator:"مشغل",
    group:"المجموعة",
    sure:"تاكيد",
  };

  private en = {
    employee_create_title: "Create New Employee",
    employee_name: "Employee Name",
    control_pannel:"control pannel",
    add_new_merit:"Add new entitlement",
    please_complete_following_error:"Please complete the following errors",
    merit_name_required:"etitlement name is required",
    value_required:"value is required",
    merit_name:" entitlement's name ",
    merit_value:"entitlement's value",
    percentage:"percent",
    add:"add",
    edit_merit:"edit entitlement",
    log_in:"log in",
    email:"email", 
    email_location_reuired:" email location reuired",
    email_must_be_correct:"Email must be correct",
    password:"password",
    password_location_reuired:"password location reuired",
    password_condition:"password must be contain x numbers and x characters",
    confirm_deletion:"are sure of the deleting process?",
    close:"close",
    delete:"delete",
    view_Ministries:"view ministries",
    add_Ministries:"add a ministry",
    full_name_employ:"full employ's name",
    full_name_mother:"full mother's name",
    phone_number:"phone numbe ",
    smart_number:"Smart Number",
    company_name:"company name",
    have_insurance:"have a insurance ?",
    date_create:"date created",
    choise:"Options",
    there_is:"exist",
    there_isnot:"Not Exist",
    edit_employee_title: "edit employee ",
    directorate_name_reuired:"directorate's name Required",
    directorate_condition:"directorate's name must be between 4 and 40 characters",
    full_name_directorate:"full directorate name",
    choose_guarantee_type:"Choose your guarantee type",
    add_new_employ:"Add a new employee",
    add_new_deduction:"add new deduction",
    deduction_name_reuired:"deduction's name is required",
    deduction_name:"deduction's name ",
    governmental:"governmental",
    edit_new_deduction:"edit deduction",
    view_deduction:"view deduction",
    add_deduction:"add deduction",
    deduction_type:" deduction type",
    deduction_percentage:"deduction percent",
    add_circuit:"add circles",
    consider_the_following:"Consider the following",
    circuit_name_reuired:"Circle 's name is required",
    circuit_name:"Circle 's name",
    edit_circuit:"Edit Circle",
    view_department:"view department",
    add_department:"add department",
    department_name:"department's name",
    placement_employe:"Employee placement",
    job_role_reuired:"Job role is required",
    department_reuired:" department required",
    job_role:"Job role",
    date_start:"starting date",
    date_end:"End date",
    state:"state",
    active:"active",
    not_active:"not active",
    edit:"edit",
    add_new_job_role:"add new Job role",
    job_role_name_reuired:"Job role name is required",
    salary_reuired:"Salary is required",
    job_role_name:"Job role name ",
    salary:"salary",
    edit_job_role:"edit Job role",
    add_job_role:"add Job role",
    first_name:"first name",
    middle_name:"second name",
    last_name:"third name",
    surname:"nickname",
    qi_card_smart_id:"QiCard smart id",
    public_employee_id:"public employee id",
    gender:"gender",
    nominal_salary:"nominal salary",
    total_salary:"total salary",
    salary_after_deduction:"salary after deduction",
    date_of_payment_of_salary:" date of payment of salary",
    view_payment_info:"View payment information",
    chosse_date:"Select Date",
    search:"search",
    search_about_employe:"Look for an employee",
    full_name:"full name",
    qi_card_account_number:"QiCard account number",
    city:"city",
    city_number:"city number",
    gov_family_id:"governmental family id",
    deduction_date:" deduction date",
    merits:"merits",
    deductions:"deductions",
    departmen:"departmen",
    ministries_number:"ministries number",
    directorate_number:" directorate number",
    predecessor_type_number:"predecessor type number",
    predecessor_taken:" predecessor_taken",
    users_number:"users_number",
    employs_number:"Number of Employees",
    beneficiaries_number:"beneficiaries number",
    Loans_info:"Loans information",
    choose_directorate:" select directorate",
    choose_ministry:"select ministry",
    employ_name_required:"Employee name is required",
    employ_name_must_be_between_4_to_40_letter:"The employee's name must be 4 to 40 characters",
    mother_name_must_be_between_4_to_40_letter:"The mother's name must be between 4 and 40 characters",
    mother_name_required:"mother_name_required",
    phone_number_accept_numbers_only:"The phone number accepts numbers only",
    phone_number_must_be_between_10_to_11_number_only:"The phone number must be between 10 and 11 digits",
    smart_number_must_be_between_4_to_40_letter:"Smart Number must be 4 to 40 characters",
    smart_number_accept_only_numbers:"smart number accept only numbers",
    smart_number_required:"smart number required",
    ministry_name_required:"ministry name required",
    main_info_about_ministry_here:"Basic information about the ministry here",
    main_info_about_payment_here:"Basic information about payments here",
    another_info_here:"Other information here",
    advance_search:"advanced search",
    department_numbers:"departments number",
    sure_password:"Confirm your password",
    first_name_location_reuired:"The first name box is required",
    add_new_username:"Add a new user",
    sure_password_must_be_identical:"Password confirmation must match correctly",
    user_validation:"User Validity",
    counter:"Accountant",
    operator:"Operator",
    group:"group",
    sure:"accent",
  };

  private kr = {
    employee_create_title: "Kurdish Create Employee..",
    employee_name: "Kurdish Employee Name",
    control_pannel:"",
    add_new_merit:"",
    please_complete_following_error:"",
    merit_name_required:"",
    value_required:"",
    merit_name:"",
    merit_value:"",
    percentage:"",
    add:"",
    edit_merit:"",
    log_in:"",
    email:"", 
    email_location_reuired:"",
    email_must_be_correct:"",
    password:"",
    password_location_reuired:"",
    password_condition:"",
    confirm_deletion:"",
    close:"",
    delete:"",
    view_Ministries:"",
    add_Ministries:"",
    full_name_employ:"",
    full_name_mother:"",
    phone_number:"",
    smart_number:"",
    company_name:"",
    have_insurance:"",
    date_create:"",
    choise:"",
    edit_employee_title: "",
    directorate_name_reuired:"",
    directorate_condition:"",
    full_name_directorate:"",
    add_new_employ:"",
    add_new_deduction:"",
    deduction_name_reuired:"",
    deduction_name:"",
    governmental:"",
    edit_new_deduction:"",
    view_deduction:"",
    add_deduction:"",
    deduction_type:"",
    deduction_percentage:"",
    add_circuit:"",
    consider_the_following:"",
    circuit_name_reuired:"",
    circuit_name:"",
    edit_circuit:"",
    view_department:"",
    add_department:"",
    department_name:"",

    placement_employe:" دامه زراندنى كارمه ند",
    job_role_reuired:"",
    department_reuired:"",
    job_role:"",
    date_start:"",
    date_end:"",
    state:"",
    active:"",
    not_active:"",
    edit:"",
    add_new_job_role:"",
    job_role_name_reuired:"",
    salary_reuired:"",
    job_role_name:"",
    salary:"",
    edit_job_role:"",
    add_job_role:"",
    first_name:"",
    middle_name:"",
    last_name:"",
    surname:"",
    qi_card_smart_id:"",
    public_employee_id:"",
    gender:"",
    nominal_salary:"",
    total_salary:"",
    salary_after_deduction:"",
    date_of_payment_of_salary:"",
    view_payment_info:"",
    chosse_date:"",
    search:"",
    search_about_employe:"",
    full_name:"",
    qi_card_account_number:"",
   
    city:"",
    city_number:"",
    gov_family_id:"",
    deduction_date:"",
    merits:"",
    deductions:"",
    departmen:"",
    ministries_number:"",
    directorate_number:"",
    predecessor_type_number:"",
    predecessor_taken:"",
    users_number:"",
    employs_number:"",
    beneficiaries_number:"",
    Loans_info:"",
    choose_directorate:"",
    choose_ministry:"",
    employ_name_required:"",
    employ_name_must_be_between_4_to_40_letter:"",
    mother_name_must_be_between_4_to_40_letter:"",
    mother_name_required:"",
    phone_number_accept_numbers_only:"",
    phone_number_must_be_between_10_to_11_number_only:"",
    smart_number_must_be_between_4_to_40_letter:"",
    smart_number_accept_only_numbers:"",
    smart_number_required:"",
    ministry_name_required:"",
    main_info_about_ministry_here:"",
    main_info_about_payment_here:"",
    another_info_here:"",
    advance_search:"",
    department_numbers:"",
    sure_password:"",
    first_name_location_reuired:"",
    add_new_username:"زيادكردنى به كارهينه رى نوى",
    sure_password_must_be_identical:"",
    user_validation:"",
    counter:"",
    operator:"",
    group:"",
    sure:"",
  };


  public getTranslate(key) {
    let lang = localStorage.getItem('lang');
    if (lang === null || lang === '' ) {
      lang = environment.defaultLang;
    }
    
    return (this[lang][key]) ? this[lang][key] : '**' + key + '**';

  }
}
